### ISSUE TITLE
显示血量的问题

### ISSUE THREAD

**Issue by 63enjoy** [Lazuplis-Mei/SuperPVZTrainner#1]
显示血量后如果点到血量条会让游戏失去焦点导致游戏暂停，解决方法是调用windows api让血量窗口点击穿透。
参考：https://blog.csdn.net/johnny_83/article/details/1702273
我试了一下qt可以做到，不知道c#行不行。

**Comment by Lazuplis-Mei** [comment]
还真的有这种问题，不过wpf的控件并非windows窗体，无法使用windows api，不过这个问题是可以解决的，你正好在我想发布的时候提了这个问题。。。。

**Comment by 63enjoy** [comment]
建议：当游戏获取焦点时血量窗口置顶，当游戏未获取焦点时血量窗口取消置顶，当游戏最小化时血量窗口隐藏，我刚刚用qt测试了一下，这样非常完美

**Comment by Lazuplis-Mei** [comment]
你也真会提要求，我已经在代码里做出改动了，你需要重新下载并编译
