### ISSUE TITLE
3/4更新内容

### ISSUE THREAD

**Issue by Lazuplis-Mei** [Lazuplis-Mei/SuperPVZTrainner#4]
3月4日更新内容
1.修复了生成罐子时，随机不可控的错误
2.对游戏版本的检查使用更宽松的模式
3.添加对GamePath游戏路径的临时存储
4.添加对带壳游戏版本的备份进程检测BackUpGameName
5.PVZTools插件中增加游戏资源下载功能，提供对主要资源下载站的访问
6.修正了载入插件对话框的小问题
7.修正主界面隐藏快捷键F2与F5
8.F5可以在修改器找到游戏至少一次，并且游戏当前是关闭状态的情况下，自动打开游戏，并等待3秒后自动打开游戏进程
9.主界面的3大功能按钮的隐藏布局修改为不占用
10.修复了操作窗口在缩放时，最小化和关闭按钮错误的问题
11.删除了针对某个人的恶意
只在代码上更新，没有实际发布的版本，提供为接下来几天的修复问题

**Comment by Greenuxx** [comment]
Hi, can you please possibly upload offsets you needed to change for the Marigold to drop different things than coins? Or even better if you could upload many other offsets too.      

嗨，您能否上传所需的偏移量，以使万寿菊掉落不同于硬币的东西？ 甚至更好，如果您还可以上传许多其他偏移量。

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Hi, can you please possibly upload offsets you needed to change for the Marigold to drop different things than coins? Or even better if you could upload many other offsets too.
> 
> 嗨，您能否上传所需的偏移量，以使万寿菊掉落不同于硬币的东西？ 甚至更好，如果您还可以上传许多其他偏移量。

I'm not very clear about what you mean by the offset. If you specifically refer to other objects, like zombies or projectiles.That will be more troublesome. Coin is a class in game, it can usually only drop objects that are also Coin class.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Hi, can you please possibly upload offsets you needed to change for the Marigold to drop different things than coins? Or even better if you could upload many other offsets too.
> 
> 嗨，您能否上传所需的偏移量，以使万寿菊掉落不同于硬币的东西？ 甚至更好，如果您还可以上传许多其他偏移量。

Or, you just want to know which memory address I changed to realize the modification of the item that the Marigold dropped

**Comment by Greenuxx** [comment]
Yes, I mean the memory address

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Yes, I mean the memory address

`PVZ.Memory.WriteByte(&H45FAFC, 218 + GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))
PVZ.Memory.WriteByte(&H45FAFF, 100 - GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))`
I am not very easy to explain the weird modification. If you understand some assembly language, you will understand what is going on here.
`PVZ.Memory.WriteByte(&H45FB0B, GetCoinTypeValue(CBMarigoldDrop2.SelectedIndex))`
Organizing these memory addresses is undoubtedly a big project.

You can find a main memory table here that records pointers to the main objects, but this only involves a small part of the static data (module address).
[https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList](url)
As for other parts that are not clearly documented, you can only find them in the code of this project.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Yes, I mean the memory address

`
PVZ.Memory.WriteByte(&H45FAFC,` 218 + GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex)) PVZ.Memory.WriteByte(&H45FAFF, 100 - GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))
`
I am not very easy to explain the weird modification. If you understand some assembly language, you will understand what is going on here.
`
PVZ.Memory.WriteByte(&H45FB0B, GetCoinTypeValue(CBMarigoldDrop2.SelectedIndex))
`
Organizing these memory addresses is undoubtedly a big project.

You can find a main memory table [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that records pointers to the main objects, but this only involves a small part of the static data (module address).
As for other parts that are not clearly documented, you can only find them in the code of this project.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Yes, I mean the memory address

`PVZ.Memory.WriteByte(&H45FAFC, 218 + GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex)) PVZ.Memory.WriteByte(&H45FAFF, 100 - GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))`
I am not very easy to explain the weird modification. If you understand some assembly language, you will understand what is going on here.

`PVZ.Memory.WriteByte(&H45FB0B, GetCoinTypeValue(CBMarigoldDrop2.SelectedIndex))`
Organizing these memory addresses is undoubtedly a big project.
You can find a main memory table [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that records pointers to the main objects, but this only involves a small part of the static data (module address).
As for other parts that are not clearly documented, you can only find them in the code of this project.

**Comment by Greenuxx** [comment]
Also, another question. Which program do you use to do these and for example, change the screen-dorr zombie to screen-door Buckethead zombie? I am right now using a program called HxD.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Also, another question. Which program do you use to do these and for example, change the screen-dorr zombie to screen-door Buckethead zombie? I am right now using a program called HxD.

I think you centainly know Cheat Engine. Although it does not provide the function to save memory to a file, in contrast, debuggers can generally do this. Here, I mean the Ollydbg. If you are referring to modifying executables statically, they no longer need modifiers.Ollydbg will be one of the very good options.

**Comment by Greenuxx** [comment]
> As for other parts that are not clearly documented, you can only find them in the code of this project.

Where can I exactly find the code of this project?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> > As for other parts that are not clearly documented, you can only find them in the code of this project.
> 
> Where can I exactly find the code of this project?

This is the current project, or, to be more straightforward, mainly WPFTrainner and PVZClass. Although these code does not follow a good design, it will does look a bit tired, but only sorts out the memory addresses in a more intuitive way will take more time.

**Comment by Greenuxx** [comment]
> > Yes, I mean the memory address
> 
> `PVZ.Memory.WriteByte(&H45FAFC, 218 + GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex)) PVZ.Memory.WriteByte(&H45FAFF, 100 - GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))`
> I am not very easy to explain the weird modification. If you understand some assembly language, you will understand what is going on here.
> 
> `PVZ.Memory.WriteByte(&H45FB0B, GetCoinTypeValue(CBMarigoldDrop2.SelectedIndex))`
> Organizing these memory addresses is undoubtedly a big project.
> You can find a main memory table [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that records pointers to the main objects, but this only involves a small part of the static data (module address).

I did what you said and I figured out plant seed is 7. It instantly crashes when Marigold is about to produce the plant seed though. I think it might be because the game doesn't know which plant seed to produce. How to set that? I want it to produce Peashooters.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> > > Yes, I mean the memory address
> > 
> > 
> > `PVZ.Memory.WriteByte(&H45FAFC, 218 + GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex)) PVZ.Memory.WriteByte(&H45FAFF, 100 - GetCoinTypeValue(CBMarigoldDrop1.SelectedIndex))`
> > I am not very easy to explain the weird modification. If you understand some assembly language, you will understand what is going on here.
> > `PVZ.Memory.WriteByte(&H45FB0B, GetCoinTypeValue(CBMarigoldDrop2.SelectedIndex))`
> > Organizing these memory addresses is undoubtedly a big project.
> > You can find a main memory table [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that records pointers to the main objects, but this only involves a small part of the static data (module address).
> 
> I did what you said and I figured out plant seed is 7. It instantly crashes when Marigold is about to produce the plant seed though. I think it might be because the game doesn't know which plant seed to produce. How to set that? I want it to produce Peashooters.

You are right, so if you want the game to know what cards should be generated, you need to modify an initialization at 0x42FFB9.Its default value is -1, which is also the direct cause of the crash.

**Comment by Greenuxx** [comment]
So I changed it to one 
![image](https://user-images.githubusercontent.com/53129102/76011122-59468580-5f14-11ea-8f37-c550d1868dda.png) and it still crashes, any idea?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> So I changed it to one
> ![image](https://user-images.githubusercontent.com/53129102/76011122-59468580-5f14-11ea-8f37-c550d1868dda.png) and it still crashes, any idea?

Uh, you should modify with the integer data type, which is 4 bytes, but you actually modified one byte

**Comment by Greenuxx** [comment]
![image](https://user-images.githubusercontent.com/53129102/76014059-42eef880-5f19-11ea-894b-ee83da18317c.png)
Like this?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/53129102/76014059-42eef880-5f19-11ea-894b-ee83da18317c.png)
> Like this?

No,This time you changed 8 bytes, please use Int32.

**Comment by Greenuxx** [comment]
Changing Int32 to 1 will change all of them to 1 though

**Comment by Greenuxx** [comment]
> Changing Int32 to 1 will change all of them to 1 though

Except Int64.

![image](https://user-images.githubusercontent.com/53129102/76015589-a7ab5280-5f1b-11ea-80fd-626d3741ec42.png)
So right now it looks like this and I still get an error when Marigold tries to produce a plant seed.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Changing Int32 to 1 will change all of them to 1 though

Yes, this part of the operation is no problem, but I suddenly realized that you seem to say that you want to generate a Coin of type 7, but the CoinType of the card is 16

**Comment by Greenuxx** [comment]
Oh really? That would explain a lot actually. I found it [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that it's 7, but I guess that is something different. I will try to change it to 16 now

**Comment by Greenuxx** [comment]
Big thank you! 
![image](https://user-images.githubusercontent.com/53129102/76016304-e261ba80-5f1c-11ea-9920-a2d2a8dd00f7.png)
Thanks for having so much patience with me! :)

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Oh really? That would explain a lot actually. I found it [here](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) that it's 7, but I guess that is something different. I will try to change it to 16 now

Actually [this part](https://github.com/Lazuplis-Mei/pvzclass/blob/master/pvzclass/MemoryAddressList) is not my submission.I will correct it.

**Comment by Greenuxx** [comment]
Just a random question, do you have PlantsVsZombies.pdb?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Just a random question, do you have PlantsVsZombies.pdb?

I hope so, but unfortunately not. All of these are the result of disassembly analysis.

**Comment by Greenuxx** [comment]
How long did it took to find how to change Screendoor Zombie to BucketHead Screendoor zombie?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> How long did it took to find how to change Screendoor Zombie to BucketHead Screendoor zombie?

There really isn't any special skill in this matter, it just happens accidentally. But according to this, if you want to let this accident happen, then all the efforts before can actually be regarded as accumulation. If you want to know a specific time. Well, about 3 months. In fact, the total time of Plus Version 95 is only over half a year l spent.

**Comment by Greenuxx** [comment]
I have one more question. What does a zombie level mean? I saw it being mentioned many times before but to this day I have no idea what it means.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> I have one more question. What does a zombie level mean? I saw it being mentioned many times before but to this day I have no idea what it means. And I am assuming proportion means how many times can the zombie appear in levels he should appear. (in %)

Yes, dangerousness,or appearance probability. That would be better understood.

**Comment by Greenuxx** [comment]
In 42FFB9, can I change the number to something that will make it random? So the Marigold will drop every time a different plant seed

**Comment by Lazuplis-Mei** [comment]
> 
> 
> In 42FFB9, can I change the number to something that will make it random? So the Marigold will drop every time a different plant seed

This requires a little bit of assembly code. I think I have to explain what exactly is 42FFB6 here.
![Y{A3$TN88L%NXBRW2K__ {O](https://user-images.githubusercontent.com/50167216/76143296-546b0880-60b1-11ea-9c33-d1da63de56ba.png)

The FFFFFFFF is 42FFB9.
![J$6MU}`AF}CHVG IR _MF(4](https://user-images.githubusercontent.com/50167216/76143337-93995980-60b1-11ea-95f1-7d841bc63f2f.png)

If you want this address to get a random value every time. I can recommend you write it like this.
![DE6Q654XI6 {YPSZ$M~5 JK](https://user-images.githubusercontent.com/50167216/76143480-baa45b00-60b2-11ea-8175-736d1a684566.png)
![3%9{DO5`9{L54D09AE9@$3J](https://user-images.githubusercontent.com/50167216/76143565-664dab00-60b3-11ea-89e8-2ea445b46abd.png)

**Comment by Greenuxx** [comment]
That worked. Thank you! Is there a way to change the order you will get plants? Like for example, I will get first Cabbage-Pult and not Peashooter as normally. I didn't find any mod like that even on Baidu and Bilibili.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> That worked. Thank you! Is there a way to change the order you will get plants? Like for example, I will get first Cabbage-Pult and not Peashooter as normally. I didn't find any mod like that even on Baidu and Bilibili.

I haven't researched this deeply. Do you want me to take some time to try? Although, I don't really want to continue doing this kind of thing. Even the modifier I am making now is just for a small promise.

**Comment by Greenuxx** [comment]
I mean, I would appreciate it. It would help a lot of people for sure. But it's your decision if you want to research it.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> I mean, I would appreciate it. It would help a lot of people for sure. But it's your decision if you want to research it.

004317F2//This is the card you dropped when you defeated the last zombie in the level.
0040690F//This is the level display of the card after you get it
00483DB6//This is the order initialization of the cards.
I will only help you here if you don't mind.

**Comment by Greenuxx** [comment]
How does the order initialization of the cards work?

**Comment by Lazuplis-Mei** [comment]
> 
> 
> How does the order initialization of the cards work?

This statement is inside a loop body, just like this.
`for(int i = 0; i <= advLevel; i++)
{
    cards[i].X = getX();
    cards[i].Y = getY();
    cards[i].Plant = i;
}`

**Comment by Greenuxx** [comment]
Ok got it. I was also trying to change Gold Magnet's selection of CoinValues that he is collecting and thought it could probably work very similarly to Marigold. Do you know how to change Gold Magnet's selection of CoinValues that he's collecting? Been trying since yesterday, but without result so far.

**Comment by Lazuplis-Mei** [comment]
> 
> 
> Ok got it. I was also trying to change Gold Magnet's selection of CoinValues that he is collecting and thought it could probably work very similarly to Marigold. Do you know how to change Gold Magnet's selection of CoinValues that he's collecting? Been trying since yesterday, but without result so far.

Sorry, I think you seem a little bit push your luck.
You can’t rely too much on others.
I have no obligation to help you so much.
At least we don't even know each other.
If you are really passionate about this, you should rely on your own efforts, otherwise it will be endless.

**Comment by Greenuxx** [comment]
Yeah sorry. I appreciate everything you helped me with. I will try my best.
